[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"

[dev-dependencies]
test_bin = "0.4.0"
predicates = "3.1.3"
rstest = "0.25.0"
assert_cmd = "2.0.17"
